sudo: required
dist: trusty
group: edge

language: scala
scala:
  - 2.11.7
# reference: https://github.com/travis-ci/travis-ci/issues/5897#issuecomment-218354129
# jdk:
#   - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

# whitelist
branches:
  only:
    - dev
  except:
    - v-dev

before_install:
  # Attempt to fix: https://github.com/travis-ci/travis-ci/issues/5545
  # reference: http://stevenschwenke.de/cannotFindSymbolInTravisAndShippable
  - export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  - export PATH="$PATH:/usr/lib/jvm/java-8-oracle/bin"
  - export java_path="/usr/lib/jvm/java-8-oracle/jre/bin/java"
  # The following line fails the build when language: scala with the following error:
  # "update-alternatives: error: error creating symbolic link `/etc/alternatives/java.dpkg-tmp': Permission denied" 
  - sudo update-alternatives --set java $java_path
  # TODO: understando how to resolve the previous error, for now we manually change the java version
  # - ln -sf $java_path /usr/bin/java
  - java -version

install:
  - make install

script:
  - make test
  - make build_container

before_deploy:
  # Clean the v-dev release and tag we are using to release development version in CI
  - sudo wget https://github.com/benchflow/benchflow/raw/dev/ci/clean_v-dev_release.sh -O /usr/bin/clean_v-dev_release.sh
  - sudo chmod +x /usr/bin/clean_v-dev_release.sh
  - export REPO_NAME=test-orchestrator
  - /usr/bin/clean_v-dev_release.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file: 
    - target/scala-2.11/benchflow-test-orchestrator.jar
  skip_cleanup: true
  on:
    tags: false
    repo: benchflow/test-orchestrator
    branch: dev
